# Generated by Django 5.1.3 on 2024-11-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resReview', '0002_restaurant_review_delete_resreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='resReview.restaurant'),
            preserve_default=False,
        ),
    ]
